/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Profile catalogue: label, core segment flag and the offer to make.
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_clients__client_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relations
         * @description Related clients per client id: explicit links first, then similar clients.
         */
        get: operations["list_relations_api_relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Seed */
        post: operations["trigger_seed_api_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Detail */
        get: operations["get_user_detail_api_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_api_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jev/analyze/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Jev Analyze User */
        post: operations["jev_analyze_user_api_jev_analyze__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jev/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Jev Analyze All
         * @description Run Jev over the transactions of every profile.
         */
        post: operations["jev_analyze_all_api_jev_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jev/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jev Client Trackers
         * @description Cached Jev trackers for the dashboard clients (null until POSTed once).
         */
        get: operations["jev_client_trackers_api_jev_clients_get"];
        put?: never;
        /**
         * Jev Score Clients
         * @description Run Jev over every dashboard client and cache the trackers.
         */
        post: operations["jev_score_clients_api_jev_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Client */
        Client: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Age */
            age: number;
            /**
             * Profiles
             * @description Highest confidence first
             */
            profiles: components["schemas"]["ProfileScore"][];
            /**
             * Monthlyspend
             * @description Last 6 months
             */
            monthlySpend: number[];
            /** Savingsrate */
            savingsRate: number;
            /** Recurringcount */
            recurringCount: number;
            /**
             * Cashshare
             * @description % of spend in cash
             */
            cashShare: number;
            /** Payday */
            payday: number;
            /** Tophabit */
            topHabit: string;
            /** Signals */
            signals: components["schemas"]["Signal"][];
            change?: components["schemas"]["HabitChange"] | null;
            /** Transactions */
            transactions: components["schemas"]["ClientTransaction"][];
            /**
             * Lastscanned
             * Format: date-time
             */
            lastScanned: string;
        };
        /** ClientTransaction */
        ClientTransaction: {
            /** Date */
            date: string;
            /** Merchant */
            merchant: string;
            /** Category */
            category: string;
            /**
             * Amount
             * @description Negative = spend
             */
            amount: number;
        };
        /** Dashboard */
        Dashboard: {
            kpis: components["schemas"]["Kpis"];
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Habittrends */
            habitTrends: {
                [key: string]: components["schemas"]["WeekPoint"][];
            };
            /** Weekdayrhythm */
            weekdayRhythm: components["schemas"]["WeekdaySpend"][];
            /**
             * Links
             * @description [clientA, clientB, reason]
             */
            links: [
                string,
                string,
                string
            ][];
            jevUsage?: components["schemas"]["JevUsage"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Habit
         * @enum {string}
         */
        Habit: "Travel" | "Investing" | "Groceries" | "Mobility" | "Eating out";
        /** HabitChange */
        HabitChange: {
            /** Habit */
            habit: string;
            /** Text */
            text: string;
            /**
             * Delta
             * @description % vs the client's own baseline
             */
            delta: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "watch" | "alert";
        };
        /** HealthCheckResponse */
        HealthCheckResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** JevResult */
        JevResult: {
            mainProfile?: components["schemas"]["ProfileId"] | null;
            /** Mainconfidence */
            mainConfidence?: number | null;
            /**
             * Trackers
             * @default []
             */
            trackers: components["schemas"]["ProfileScore"][];
            /** Incomeregularity */
            incomeRegularity?: number | null;
            /** Model */
            model?: string | null;
            /** Error */
            error?: string | null;
        };
        /** JevTrackers */
        JevTrackers: {
            /**
             * Analyzedat
             * Format: date-time
             */
            analyzedAt: string;
            /** Clients */
            clients: {
                [key: string]: components["schemas"]["JevResult"];
            };
        };
        /** JevUsage */
        JevUsage: {
            /** Requests */
            requests: number;
            /** Clientsanalysed */
            clientsAnalysed: number;
            /** Inputtokens */
            inputTokens: number;
            /** Outputtokens */
            outputTokens: number;
            /** Costusd */
            costUsd: number;
        };
        /** Kpis */
        Kpis: {
            /** Clientstracked */
            clientsTracked: number;
            /** Profilesdetected */
            profilesDetected: number;
            /** Habitchanges */
            habitChanges: number;
            /** Openopportunities */
            openOpportunities: number;
        };
        /** ProfileDef */
        ProfileDef: {
            id: components["schemas"]["ProfileId"];
            /** Label */
            label: string;
            /** Core */
            core: boolean;
            /** Offer */
            offer: string;
        };
        /**
         * ProfileId
         * @enum {string}
         */
        ProfileId: "student" | "young-investor" | "investor" | "holiday" | "family" | "homebuyer" | "commuter" | "freelancer" | "saver" | "financial-stress" | "retiree" | "big-event";
        /** ProfileScore */
        ProfileScore: {
            id: components["schemas"]["ProfileId"];
            /** Confidence */
            confidence: number;
        };
        /** Relation */
        Relation: {
            /** Clientid */
            clientId: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "linked" | "similar";
            /** Reason */
            reason: string;
            /** Score */
            score: number;
        };
        /** Segment */
        Segment: {
            id: components["schemas"]["ProfileId"];
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** Signal */
        Signal: {
            /** Text */
            text: string;
            /**
             * Weight
             * @description 0..1 contribution to the profile confidence
             */
            weight: number;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Amount */
            amount: number | string;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Transaction Type */
            transaction_type: string;
            /**
             * Status
             * @default completed
             */
            status: string;
            /** Description */
            description?: string | null;
            /** User Id */
            user_id: number;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /** Amount */
            amount: string;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Transaction Type */
            transaction_type: string;
            /**
             * Status
             * @default completed
             */
            status: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Financial Situation
             * @default balanced
             */
            financial_situation: string | null;
            /**
             * Is Student
             * @default false
             */
            is_student: boolean;
            /**
             * Is Unemployed
             * @default false
             */
            is_unemployed: boolean;
            /**
             * Is High Income
             * @default false
             */
            is_high_income: boolean;
            /**
             * Discretionary Spender
             * @default moderate
             */
            discretionary_spender: string | null;
            /**
             * Main Transportation
             * @default car
             */
            main_transportation: string | null;
            /**
             * Children Count
             * @default 0
             */
            children_count: number;
            /**
             * In Couple
             * @default false
             */
            in_couple: boolean;
            /**
             * Has Insurance
             * @default true
             */
            has_insurance: boolean;
            /**
             * Housing Status
             * @default renter
             */
            housing_status: string | null;
            /**
             * Age Range
             * @default 26-35
             */
            age_range: string | null;
            /**
             * Savings Goal
             * @default emergency_fund
             */
            savings_goal: string | null;
            /**
             * Risk Tolerance
             * @default medium
             */
            risk_tolerance: string | null;
        };
        /** UserDetailResponse */
        UserDetailResponse: {
            /** Name */
            name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Financial Situation
             * @default balanced
             */
            financial_situation: string | null;
            /**
             * Is Student
             * @default false
             */
            is_student: boolean;
            /**
             * Is Unemployed
             * @default false
             */
            is_unemployed: boolean;
            /**
             * Is High Income
             * @default false
             */
            is_high_income: boolean;
            /**
             * Discretionary Spender
             * @default moderate
             */
            discretionary_spender: string | null;
            /**
             * Main Transportation
             * @default car
             */
            main_transportation: string | null;
            /**
             * Children Count
             * @default 0
             */
            children_count: number;
            /**
             * In Couple
             * @default false
             */
            in_couple: boolean;
            /**
             * Has Insurance
             * @default true
             */
            has_insurance: boolean;
            /**
             * Housing Status
             * @default renter
             */
            housing_status: string | null;
            /**
             * Age Range
             * @default 26-35
             */
            age_range: string | null;
            /**
             * Savings Goal
             * @default emergency_fund
             */
            savings_goal: string | null;
            /**
             * Risk Tolerance
             * @default medium
             */
            risk_tolerance: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Transactions
             * @default []
             */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        /** UserResponse */
        UserResponse: {
            /** Name */
            name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email?: string | null;
            /** Address */
            address?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Financial Situation
             * @default balanced
             */
            financial_situation: string | null;
            /**
             * Is Student
             * @default false
             */
            is_student: boolean;
            /**
             * Is Unemployed
             * @default false
             */
            is_unemployed: boolean;
            /**
             * Is High Income
             * @default false
             */
            is_high_income: boolean;
            /**
             * Discretionary Spender
             * @default moderate
             */
            discretionary_spender: string | null;
            /**
             * Main Transportation
             * @default car
             */
            main_transportation: string | null;
            /**
             * Children Count
             * @default 0
             */
            children_count: number;
            /**
             * In Couple
             * @default false
             */
            in_couple: boolean;
            /**
             * Has Insurance
             * @default true
             */
            has_insurance: boolean;
            /**
             * Housing Status
             * @default renter
             */
            housing_status: string | null;
            /**
             * Age Range
             * @default 26-35
             */
            age_range: string | null;
            /**
             * Savings Goal
             * @default emergency_fund
             */
            savings_goal: string | null;
            /**
             * Risk Tolerance
             * @default medium
             */
            risk_tolerance: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeekPoint */
        WeekPoint: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Spend */
            spend: number;
            /** Baseline */
            baseline: number;
        };
        /** WeekdaySpend */
        WeekdaySpend: {
            /** Day */
            day: string;
            /** Spend */
            spend: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDef"][];
                };
            };
        };
    };
    list_clients_api_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    get_client_api_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relations_api_relations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Relation"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    trigger_seed_api_seed_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_detail_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_transactions_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jev_analyze_user_api_jev_analyze__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jev_analyze_all_api_jev_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    jev_client_trackers_api_jev_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JevTrackers"] | null;
                };
            };
        };
    };
    jev_score_clients_api_jev_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JevTrackers"];
                };
            };
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const habitValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Habit"]> = ["Travel", "Investing", "Groceries", "Mobility", "Eating out"];
export const habitChangeSeverityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HabitChange"]["severity"]> = ["info", "watch", "alert"];
export const profileIdValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ProfileId"]> = ["student", "young-investor", "investor", "holiday", "family", "homebuyer", "commuter", "freelancer", "saver", "financial-stress", "retiree", "big-event"];
export const relationKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Relation"]["kind"]> = ["linked", "similar"];
